//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorInboundData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ErrorInboundData()
        {
            this.ErrorSuggestions = new HashSet<ErrorSuggestion>();
        }
    
        public System.Guid Id { get; set; }
        public string ErrorType { get; set; }
        public string DataType { get; set; }
        public string DataKey { get; set; }
        public string DataValue { get; set; }
        public string DataPath { get; set; }
        public string SysErrorMsg { get; set; }
        public string CustomErrorMsg { get; set; }
        public bool IsRectifiable { get; set; }
        public System.Guid ErrorXmlId { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual ErrorXml ErrorXml { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ErrorSuggestion> ErrorSuggestions { get; set; }
    }
}
