//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorXml
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ErrorXml()
        {
            this.ErrorInboundDatas = new HashSet<ErrorInboundData>();
        }
    
        public System.Guid Id { get; set; }
        public string Client_Code { get; set; }
        public string Warehouse_Code { get; set; }
        public string XmlContent { get; set; }
        public string DocumentUniqueId { get; set; }
        public string DocumentType { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ErrorInboundData> ErrorInboundDatas { get; set; }
    }
}
