//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error_Suggestion_InboundData_Mapper
    {
        public System.Guid Id { get; set; }
        public System.Guid ErrorSuggestionId { get; set; }
        public System.Guid ErrorInboundDataId { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual ErrorInboundData ErrorInboundData { get; set; }
        public virtual ErrorSuggestion ErrorSuggestion { get; set; }
    }
}
