//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location_SYD
    {
        public int location_id { get; set; }
        public string location { get; set; }
        public string postcode { get; set; }
        public string state { get; set; }
        public string nearest_depot { get; set; }
        public string servicing_city { get; set; }
        public string direct_zone { get; set; }
        public string onforwarding_zone { get; set; }
        public string alt_servicing_city { get; set; }
        public string alt_onforwarding_zone { get; set; }
        public string alt_route_states { get; set; }
        public Nullable<short> lead_days_EXP { get; set; }
        public Nullable<short> lead_days_PAC { get; set; }
        public Nullable<short> lead_days_1KN { get; set; }
        public Nullable<short> lead_days_1PN { get; set; }
    }
}
