//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class STEInterfacesEntities : DbContext
    {
        public STEInterfacesEntities()
            : base("name=STEInterfacesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationEventMaster> ApplicationEventMasters { get; set; }
        public virtual DbSet<ApplicationLog> ApplicationLogs { get; set; }
        public virtual DbSet<ApplicationMaster> ApplicationMasters { get; set; }
        public virtual DbSet<ErrorInboundData> ErrorInboundDatas { get; set; }
        public virtual DbSet<ErrorSuggestion> ErrorSuggestions { get; set; }
        public virtual DbSet<ErrorXml> ErrorXmls { get; set; }
        public virtual DbSet<Location_SYD> Location_SYD { get; set; }
    }
}
