//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8933
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace ValidationRuleEngine.DataFiles.SalesOrder
{
}

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class SalesOrders {
    
    private SalesOrdersOrderHeader[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OrderHeader", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SalesOrdersOrderHeader[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SalesOrdersOrderHeader {
    
    private string hostIDField;
    
    private string companyCodeField;
    
    private string clientCodeField;
    
    private string warehouseCodeField;
    
    private string orderNumberField;
    
    private string origOrderNumberField;
    
    private string accellosOrderNumberField;
    
    private string purchaseOrderNumberField;
    
    private string customerReferenceField;
    
    private string clientASNNumberField;
    
    private object asnIDField;
    
    private string clientEDIAddressField;
    
    private string retailerEDIAddressField;
    
    private string retailerNumberField;
    
    private string promotionNumberField;
    
    private string vendorNumberField;
    
    private bool invoiceRequiredField;
    
    private bool asnRequiredField;
    
    private bool packSlipRequiredField;
    
    private bool priceTicketRequiredField;
    
    private bool salesOrderAcknowledgementRequiredField;
    
    private bool pickConfirmationAcknowledgementRequiredField;
    
    private bool asnAcknowledgementRequiredField;
    
    private bool orderConfirmedField;
    
    private bool despatchEmailNotificationRequiredField;
    
    private string orderTypeField;
    
    private string orderClassField;
    
    private System.DateTime orderDateField;
    
    private bool orderDateFieldSpecified;
    
    private System.DateTime customerOrderDateField;
    
    private bool customerOrderDateFieldSpecified;
    
    private System.DateTime deliveryDateField;
    
    private bool deliveryDateFieldSpecified;
    
    private System.DateTime requestedArrivalDateField;
    
    private bool requestedArrivalDateFieldSpecified;
    
    private System.DateTime deliveryDateBeforeField;
    
    private bool deliveryDateBeforeFieldSpecified;
    
    private System.DateTime deliveryDateAfterField;
    
    private bool deliveryDateAfterFieldSpecified;
    
    private System.DateTime despatchDateField;
    
    private bool despatchDateFieldSpecified;
    
    private System.DateTime shipDateField;
    
    private bool shipDateFieldSpecified;
    
    private System.DateTime earliestShipDateField;
    
    private bool earliestShipDateFieldSpecified;
    
    private System.DateTime latestShipDateField;
    
    private bool latestShipDateFieldSpecified;
    
    private System.DateTime releaseDateField;
    
    private bool releaseDateFieldSpecified;
    
    private System.DateTime cancellationDateField;
    
    private bool cancellationDateFieldSpecified;
    
    private System.DateTime etaDateField;
    
    private bool etaDateFieldSpecified;
    
    private string cutOffTimeField;
    
    private string shipToCodeField;
    
    private string shipToDepartmentField;
    
    private string shipToName1Field;
    
    private string shipToName2Field;
    
    private string shipToAddress1Field;
    
    private string shipToAddress2Field;
    
    private string shipToAddress3Field;
    
    private string shipToLocationField;
    
    private string shipToPostcodeField;
    
    private string shipToStateField;
    
    private string shipToCountryCodeField;
    
    private string shipToCountryNameField;
    
    private string shipToPhoneNumberField;
    
    private string shipToAccountNumberField;
    
    private string shipToEmailAddressField;
    
    private string shipToEmailSalutationField;
    
    private string shipToDepotField;
    
    private string deliverToCodeField;
    
    private string deliverToName1Field;
    
    private string deliverToName2Field;
    
    private string deliverToAddress1Field;
    
    private string deliverToAddress2Field;
    
    private string deliverToAddress3Field;
    
    private string deliverToLocationField;
    
    private string deliverToPostcodeField;
    
    private string deliverToStateField;
    
    private string deliverToCountryCodeField;
    
    private string deliverToCountryNameField;
    
    private string deliverToPhoneNumberField;
    
    private string deliverToAccountNumberField;
    
    private string deliverToEmailAddressField;
    
    private string deliverToEmailSalutationField;
    
    private string billToCodeField;
    
    private string billToName1Field;
    
    private string billToName2Field;
    
    private string billToAddress1Field;
    
    private string billToAddress2Field;
    
    private string billToAddress3Field;
    
    private string billToLocationField;
    
    private string billToPostcodeField;
    
    private string billToStateField;
    
    private string billToCountryCodeField;
    
    private string billToCountryNameField;
    
    private string billToPhoneNumberField;
    
    private string billToAccountNumberField;
    
    private string billToEmailAddressField;
    
    private string billToEmailSalutationField;
    
    private string departmentNumberField;
    
    private string departmentNameField;
    
    private string specialInstructions1Field;
    
    private string specialInstructions2Field;
    
    private string specialInstructions3Field;
    
    private string warehouseInstructions1Field;
    
    private string warehouseInstructions2Field;
    
    private string referenceField1Field;
    
    private string referenceField2Field;
    
    private string referenceField3Field;
    
    private string referenceField4Field;
    
    private string referenceField5Field;
    
    private string labelText1Field;
    
    private string labelText2Field;
    
    private string labelText3Field;
    
    private string sendersReferenceField;
    
    private string labelCodeField;
    
    private string advertisedDateField;
    
    private string abnField;
    
    private string invoiceNumberField;
    
    private System.DateTime invoiceDateField;
    
    private bool invoiceDateFieldSpecified;
    
    private System.DateTime invoiceDueDateField;
    
    private bool invoiceDueDateFieldSpecified;
    
    private string invoiceHeaderTextField;
    
    private string invoiceTermsField;
    
    private string freightDescriptionField;
    
    private float freightTotalField;
    
    private float surchargeTotalField;
    
    private float miscellaneousTotal1Field;
    
    private float miscellaneousTotal2Field;
    
    private float gstTotalField;
    
    private float subTotalField;
    
    private float invoiceTotalField;
    
    private string currencyCodeField;
    
    private float totalWeightField;
    
    private float totalVolumeField;
    
    private float totalQuantityField;
    
    private float totalCartonsField;
    
    private string serviceCodeField;
    
    private string carrierAbbreviationField;
    
    private bool useAlternateDespatchIDField;
    
    private bool specialServiceFlagField;
    
    private string payerTypeField;
    
    private string payerName1Field;
    
    private string payerName2Field;
    
    private string payerAccountNumberField;
    
    private string userDefinedField1Field;
    
    private string userDefinedField2Field;
    
    private string userDefinedField3Field;
    
    private string userDefinedField4Field;
    
    private string userDefinedField5Field;
    
    private string userDefinedField6Field;
    
    private string userDefinedField7Field;
    
    private string userDefinedField8Field;
    
    private string userDefinedField9Field;
    
    private string userDefinedField10Field;
    
    private string connoteNumberField;
    
    private string originCodeField;
    
    private SalesOrdersOrderHeaderOrderDetail orderDetailField;
    
    public SalesOrdersOrderHeader() {
        this.invoiceRequiredField = false;
        this.asnRequiredField = false;
        this.packSlipRequiredField = false;
        this.priceTicketRequiredField = false;
        this.salesOrderAcknowledgementRequiredField = false;
        this.pickConfirmationAcknowledgementRequiredField = false;
        this.asnAcknowledgementRequiredField = false;
        this.orderConfirmedField = false;
        this.despatchEmailNotificationRequiredField = false;
        this.freightTotalField = ((float)(0F));
        this.surchargeTotalField = ((float)(0F));
        this.miscellaneousTotal1Field = ((float)(0F));
        this.miscellaneousTotal2Field = ((float)(0F));
        this.gstTotalField = ((float)(0F));
        this.subTotalField = ((float)(0F));
        this.invoiceTotalField = ((float)(0F));
        this.totalWeightField = ((float)(0F));
        this.totalVolumeField = ((float)(0F));
        this.totalQuantityField = ((float)(0F));
        this.totalCartonsField = ((float)(0F));
        this.useAlternateDespatchIDField = false;
        this.specialServiceFlagField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string hostID {
        get {
            return this.hostIDField;
        }
        set {
            this.hostIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string companyCode {
        get {
            return this.companyCodeField;
        }
        set {
            this.companyCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string clientCode {
        get {
            return this.clientCodeField;
        }
        set {
            this.clientCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string warehouseCode {
        get {
            return this.warehouseCodeField;
        }
        set {
            this.warehouseCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string orderNumber {
        get {
            return this.orderNumberField;
        }
        set {
            this.orderNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string origOrderNumber {
        get {
            return this.origOrderNumberField;
        }
        set {
            this.origOrderNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
    public string accellosOrderNumber {
        get {
            return this.accellosOrderNumberField;
        }
        set {
            this.accellosOrderNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string purchaseOrderNumber {
        get {
            return this.purchaseOrderNumberField;
        }
        set {
            this.purchaseOrderNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string customerReference {
        get {
            return this.customerReferenceField;
        }
        set {
            this.customerReferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string clientASNNumber {
        get {
            return this.clientASNNumberField;
        }
        set {
            this.clientASNNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object asnID {
        get {
            return this.asnIDField;
        }
        set {
            this.asnIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string clientEDIAddress {
        get {
            return this.clientEDIAddressField;
        }
        set {
            this.clientEDIAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string retailerEDIAddress {
        get {
            return this.retailerEDIAddressField;
        }
        set {
            this.retailerEDIAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string retailerNumber {
        get {
            return this.retailerNumberField;
        }
        set {
            this.retailerNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string promotionNumber {
        get {
            return this.promotionNumberField;
        }
        set {
            this.promotionNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string vendorNumber {
        get {
            return this.vendorNumberField;
        }
        set {
            this.vendorNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool invoiceRequired {
        get {
            return this.invoiceRequiredField;
        }
        set {
            this.invoiceRequiredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool asnRequired {
        get {
            return this.asnRequiredField;
        }
        set {
            this.asnRequiredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool packSlipRequired {
        get {
            return this.packSlipRequiredField;
        }
        set {
            this.packSlipRequiredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool priceTicketRequired {
        get {
            return this.priceTicketRequiredField;
        }
        set {
            this.priceTicketRequiredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool salesOrderAcknowledgementRequired {
        get {
            return this.salesOrderAcknowledgementRequiredField;
        }
        set {
            this.salesOrderAcknowledgementRequiredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool pickConfirmationAcknowledgementRequired {
        get {
            return this.pickConfirmationAcknowledgementRequiredField;
        }
        set {
            this.pickConfirmationAcknowledgementRequiredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool asnAcknowledgementRequired {
        get {
            return this.asnAcknowledgementRequiredField;
        }
        set {
            this.asnAcknowledgementRequiredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool orderConfirmed {
        get {
            return this.orderConfirmedField;
        }
        set {
            this.orderConfirmedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool despatchEmailNotificationRequired {
        get {
            return this.despatchEmailNotificationRequiredField;
        }
        set {
            this.despatchEmailNotificationRequiredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string orderType {
        get {
            return this.orderTypeField;
        }
        set {
            this.orderTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string orderClass {
        get {
            return this.orderClassField;
        }
        set {
            this.orderClassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime orderDate {
        get {
            return this.orderDateField;
        }
        set {
            this.orderDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool orderDateSpecified {
        get {
            return this.orderDateFieldSpecified;
        }
        set {
            this.orderDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime customerOrderDate {
        get {
            return this.customerOrderDateField;
        }
        set {
            this.customerOrderDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool customerOrderDateSpecified {
        get {
            return this.customerOrderDateFieldSpecified;
        }
        set {
            this.customerOrderDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime deliveryDate {
        get {
            return this.deliveryDateField;
        }
        set {
            this.deliveryDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool deliveryDateSpecified {
        get {
            return this.deliveryDateFieldSpecified;
        }
        set {
            this.deliveryDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime requestedArrivalDate {
        get {
            return this.requestedArrivalDateField;
        }
        set {
            this.requestedArrivalDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool requestedArrivalDateSpecified {
        get {
            return this.requestedArrivalDateFieldSpecified;
        }
        set {
            this.requestedArrivalDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime deliveryDateBefore {
        get {
            return this.deliveryDateBeforeField;
        }
        set {
            this.deliveryDateBeforeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool deliveryDateBeforeSpecified {
        get {
            return this.deliveryDateBeforeFieldSpecified;
        }
        set {
            this.deliveryDateBeforeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime deliveryDateAfter {
        get {
            return this.deliveryDateAfterField;
        }
        set {
            this.deliveryDateAfterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool deliveryDateAfterSpecified {
        get {
            return this.deliveryDateAfterFieldSpecified;
        }
        set {
            this.deliveryDateAfterFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime despatchDate {
        get {
            return this.despatchDateField;
        }
        set {
            this.despatchDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool despatchDateSpecified {
        get {
            return this.despatchDateFieldSpecified;
        }
        set {
            this.despatchDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime shipDate {
        get {
            return this.shipDateField;
        }
        set {
            this.shipDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool shipDateSpecified {
        get {
            return this.shipDateFieldSpecified;
        }
        set {
            this.shipDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime earliestShipDate {
        get {
            return this.earliestShipDateField;
        }
        set {
            this.earliestShipDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool earliestShipDateSpecified {
        get {
            return this.earliestShipDateFieldSpecified;
        }
        set {
            this.earliestShipDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime latestShipDate {
        get {
            return this.latestShipDateField;
        }
        set {
            this.latestShipDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool latestShipDateSpecified {
        get {
            return this.latestShipDateFieldSpecified;
        }
        set {
            this.latestShipDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime releaseDate {
        get {
            return this.releaseDateField;
        }
        set {
            this.releaseDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool releaseDateSpecified {
        get {
            return this.releaseDateFieldSpecified;
        }
        set {
            this.releaseDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime cancellationDate {
        get {
            return this.cancellationDateField;
        }
        set {
            this.cancellationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool cancellationDateSpecified {
        get {
            return this.cancellationDateFieldSpecified;
        }
        set {
            this.cancellationDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime etaDate {
        get {
            return this.etaDateField;
        }
        set {
            this.etaDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool etaDateSpecified {
        get {
            return this.etaDateFieldSpecified;
        }
        set {
            this.etaDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string cutOffTime {
        get {
            return this.cutOffTimeField;
        }
        set {
            this.cutOffTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shipToCode {
        get {
            return this.shipToCodeField;
        }
        set {
            this.shipToCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shipToDepartment {
        get {
            return this.shipToDepartmentField;
        }
        set {
            this.shipToDepartmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shipToName1 {
        get {
            return this.shipToName1Field;
        }
        set {
            this.shipToName1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shipToName2 {
        get {
            return this.shipToName2Field;
        }
        set {
            this.shipToName2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shipToAddress1 {
        get {
            return this.shipToAddress1Field;
        }
        set {
            this.shipToAddress1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shipToAddress2 {
        get {
            return this.shipToAddress2Field;
        }
        set {
            this.shipToAddress2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shipToAddress3 {
        get {
            return this.shipToAddress3Field;
        }
        set {
            this.shipToAddress3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shipToLocation {
        get {
            return this.shipToLocationField;
        }
        set {
            this.shipToLocationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shipToPostcode {
        get {
            return this.shipToPostcodeField;
        }
        set {
            this.shipToPostcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shipToState {
        get {
            return this.shipToStateField;
        }
        set {
            this.shipToStateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shipToCountryCode {
        get {
            return this.shipToCountryCodeField;
        }
        set {
            this.shipToCountryCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shipToCountryName {
        get {
            return this.shipToCountryNameField;
        }
        set {
            this.shipToCountryNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shipToPhoneNumber {
        get {
            return this.shipToPhoneNumberField;
        }
        set {
            this.shipToPhoneNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shipToAccountNumber {
        get {
            return this.shipToAccountNumberField;
        }
        set {
            this.shipToAccountNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shipToEmailAddress {
        get {
            return this.shipToEmailAddressField;
        }
        set {
            this.shipToEmailAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shipToEmailSalutation {
        get {
            return this.shipToEmailSalutationField;
        }
        set {
            this.shipToEmailSalutationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shipToDepot {
        get {
            return this.shipToDepotField;
        }
        set {
            this.shipToDepotField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string deliverToCode {
        get {
            return this.deliverToCodeField;
        }
        set {
            this.deliverToCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string deliverToName1 {
        get {
            return this.deliverToName1Field;
        }
        set {
            this.deliverToName1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string deliverToName2 {
        get {
            return this.deliverToName2Field;
        }
        set {
            this.deliverToName2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string deliverToAddress1 {
        get {
            return this.deliverToAddress1Field;
        }
        set {
            this.deliverToAddress1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string deliverToAddress2 {
        get {
            return this.deliverToAddress2Field;
        }
        set {
            this.deliverToAddress2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string deliverToAddress3 {
        get {
            return this.deliverToAddress3Field;
        }
        set {
            this.deliverToAddress3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string deliverToLocation {
        get {
            return this.deliverToLocationField;
        }
        set {
            this.deliverToLocationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string deliverToPostcode {
        get {
            return this.deliverToPostcodeField;
        }
        set {
            this.deliverToPostcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string deliverToState {
        get {
            return this.deliverToStateField;
        }
        set {
            this.deliverToStateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string deliverToCountryCode {
        get {
            return this.deliverToCountryCodeField;
        }
        set {
            this.deliverToCountryCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string deliverToCountryName {
        get {
            return this.deliverToCountryNameField;
        }
        set {
            this.deliverToCountryNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string deliverToPhoneNumber {
        get {
            return this.deliverToPhoneNumberField;
        }
        set {
            this.deliverToPhoneNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string deliverToAccountNumber {
        get {
            return this.deliverToAccountNumberField;
        }
        set {
            this.deliverToAccountNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string deliverToEmailAddress {
        get {
            return this.deliverToEmailAddressField;
        }
        set {
            this.deliverToEmailAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string deliverToEmailSalutation {
        get {
            return this.deliverToEmailSalutationField;
        }
        set {
            this.deliverToEmailSalutationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string billToCode {
        get {
            return this.billToCodeField;
        }
        set {
            this.billToCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string billToName1 {
        get {
            return this.billToName1Field;
        }
        set {
            this.billToName1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string billToName2 {
        get {
            return this.billToName2Field;
        }
        set {
            this.billToName2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string billToAddress1 {
        get {
            return this.billToAddress1Field;
        }
        set {
            this.billToAddress1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string billToAddress2 {
        get {
            return this.billToAddress2Field;
        }
        set {
            this.billToAddress2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string billToAddress3 {
        get {
            return this.billToAddress3Field;
        }
        set {
            this.billToAddress3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string billToLocation {
        get {
            return this.billToLocationField;
        }
        set {
            this.billToLocationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string billToPostcode {
        get {
            return this.billToPostcodeField;
        }
        set {
            this.billToPostcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string billToState {
        get {
            return this.billToStateField;
        }
        set {
            this.billToStateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string billToCountryCode {
        get {
            return this.billToCountryCodeField;
        }
        set {
            this.billToCountryCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string billToCountryName {
        get {
            return this.billToCountryNameField;
        }
        set {
            this.billToCountryNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string billToPhoneNumber {
        get {
            return this.billToPhoneNumberField;
        }
        set {
            this.billToPhoneNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string billToAccountNumber {
        get {
            return this.billToAccountNumberField;
        }
        set {
            this.billToAccountNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string billToEmailAddress {
        get {
            return this.billToEmailAddressField;
        }
        set {
            this.billToEmailAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string billToEmailSalutation {
        get {
            return this.billToEmailSalutationField;
        }
        set {
            this.billToEmailSalutationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string departmentNumber {
        get {
            return this.departmentNumberField;
        }
        set {
            this.departmentNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string departmentName {
        get {
            return this.departmentNameField;
        }
        set {
            this.departmentNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string specialInstructions1 {
        get {
            return this.specialInstructions1Field;
        }
        set {
            this.specialInstructions1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string specialInstructions2 {
        get {
            return this.specialInstructions2Field;
        }
        set {
            this.specialInstructions2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string specialInstructions3 {
        get {
            return this.specialInstructions3Field;
        }
        set {
            this.specialInstructions3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string warehouseInstructions1 {
        get {
            return this.warehouseInstructions1Field;
        }
        set {
            this.warehouseInstructions1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string warehouseInstructions2 {
        get {
            return this.warehouseInstructions2Field;
        }
        set {
            this.warehouseInstructions2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string referenceField1 {
        get {
            return this.referenceField1Field;
        }
        set {
            this.referenceField1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string referenceField2 {
        get {
            return this.referenceField2Field;
        }
        set {
            this.referenceField2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string referenceField3 {
        get {
            return this.referenceField3Field;
        }
        set {
            this.referenceField3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string referenceField4 {
        get {
            return this.referenceField4Field;
        }
        set {
            this.referenceField4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string referenceField5 {
        get {
            return this.referenceField5Field;
        }
        set {
            this.referenceField5Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string labelText1 {
        get {
            return this.labelText1Field;
        }
        set {
            this.labelText1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string labelText2 {
        get {
            return this.labelText2Field;
        }
        set {
            this.labelText2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string labelText3 {
        get {
            return this.labelText3Field;
        }
        set {
            this.labelText3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sendersReference {
        get {
            return this.sendersReferenceField;
        }
        set {
            this.sendersReferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string labelCode {
        get {
            return this.labelCodeField;
        }
        set {
            this.labelCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string advertisedDate {
        get {
            return this.advertisedDateField;
        }
        set {
            this.advertisedDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string abn {
        get {
            return this.abnField;
        }
        set {
            this.abnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string invoiceNumber {
        get {
            return this.invoiceNumberField;
        }
        set {
            this.invoiceNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime invoiceDate {
        get {
            return this.invoiceDateField;
        }
        set {
            this.invoiceDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool invoiceDateSpecified {
        get {
            return this.invoiceDateFieldSpecified;
        }
        set {
            this.invoiceDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime invoiceDueDate {
        get {
            return this.invoiceDueDateField;
        }
        set {
            this.invoiceDueDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool invoiceDueDateSpecified {
        get {
            return this.invoiceDueDateFieldSpecified;
        }
        set {
            this.invoiceDueDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string invoiceHeaderText {
        get {
            return this.invoiceHeaderTextField;
        }
        set {
            this.invoiceHeaderTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string invoiceTerms {
        get {
            return this.invoiceTermsField;
        }
        set {
            this.invoiceTermsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string freightDescription {
        get {
            return this.freightDescriptionField;
        }
        set {
            this.freightDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float freightTotal {
        get {
            return this.freightTotalField;
        }
        set {
            this.freightTotalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float surchargeTotal {
        get {
            return this.surchargeTotalField;
        }
        set {
            this.surchargeTotalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float miscellaneousTotal1 {
        get {
            return this.miscellaneousTotal1Field;
        }
        set {
            this.miscellaneousTotal1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float miscellaneousTotal2 {
        get {
            return this.miscellaneousTotal2Field;
        }
        set {
            this.miscellaneousTotal2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float gstTotal {
        get {
            return this.gstTotalField;
        }
        set {
            this.gstTotalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float subTotal {
        get {
            return this.subTotalField;
        }
        set {
            this.subTotalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float invoiceTotal {
        get {
            return this.invoiceTotalField;
        }
        set {
            this.invoiceTotalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string currencyCode {
        get {
            return this.currencyCodeField;
        }
        set {
            this.currencyCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float totalWeight {
        get {
            return this.totalWeightField;
        }
        set {
            this.totalWeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float totalVolume {
        get {
            return this.totalVolumeField;
        }
        set {
            this.totalVolumeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float totalQuantity {
        get {
            return this.totalQuantityField;
        }
        set {
            this.totalQuantityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float totalCartons {
        get {
            return this.totalCartonsField;
        }
        set {
            this.totalCartonsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string serviceCode {
        get {
            return this.serviceCodeField;
        }
        set {
            this.serviceCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string carrierAbbreviation {
        get {
            return this.carrierAbbreviationField;
        }
        set {
            this.carrierAbbreviationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool useAlternateDespatchID {
        get {
            return this.useAlternateDespatchIDField;
        }
        set {
            this.useAlternateDespatchIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool specialServiceFlag {
        get {
            return this.specialServiceFlagField;
        }
        set {
            this.specialServiceFlagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string payerType {
        get {
            return this.payerTypeField;
        }
        set {
            this.payerTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string payerName1 {
        get {
            return this.payerName1Field;
        }
        set {
            this.payerName1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string payerName2 {
        get {
            return this.payerName2Field;
        }
        set {
            this.payerName2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string payerAccountNumber {
        get {
            return this.payerAccountNumberField;
        }
        set {
            this.payerAccountNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string userDefinedField1 {
        get {
            return this.userDefinedField1Field;
        }
        set {
            this.userDefinedField1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string userDefinedField2 {
        get {
            return this.userDefinedField2Field;
        }
        set {
            this.userDefinedField2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string userDefinedField3 {
        get {
            return this.userDefinedField3Field;
        }
        set {
            this.userDefinedField3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string userDefinedField4 {
        get {
            return this.userDefinedField4Field;
        }
        set {
            this.userDefinedField4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string userDefinedField5 {
        get {
            return this.userDefinedField5Field;
        }
        set {
            this.userDefinedField5Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string userDefinedField6 {
        get {
            return this.userDefinedField6Field;
        }
        set {
            this.userDefinedField6Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string userDefinedField7 {
        get {
            return this.userDefinedField7Field;
        }
        set {
            this.userDefinedField7Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string userDefinedField8 {
        get {
            return this.userDefinedField8Field;
        }
        set {
            this.userDefinedField8Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string userDefinedField9 {
        get {
            return this.userDefinedField9Field;
        }
        set {
            this.userDefinedField9Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string userDefinedField10 {
        get {
            return this.userDefinedField10Field;
        }
        set {
            this.userDefinedField10Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string connoteNumber {
        get {
            return this.connoteNumberField;
        }
        set {
            this.connoteNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string originCode {
        get {
            return this.originCodeField;
        }
        set {
            this.originCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SalesOrdersOrderHeaderOrderDetail OrderDetail {
        get {
            return this.orderDetailField;
        }
        set {
            this.orderDetailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SalesOrdersOrderHeaderOrderDetail {
    
    private string lineNumberField;
    
    private string customerLineNumberField;
    
    private string parentLineNumberField;
    
    private string productCodeField;
    
    private string customerProductCodeField;
    
    private string upcCodeField;
    
    private string productDescriptionField;
    
    private string sizeField;
    
    private string styleField;
    
    private string colorField;
    
    private string category1Field;
    
    private string category2Field;
    
    private string category3Field;
    
    private string category4Field;
    
    private string ageCodeField;
    
    private string seasonCodeField;
    
    private float packingQuantityField;
    
    private float quantityOrderedField;
    
    private float quantityShippedField;
    
    private float quantityBackOrderedField;
    
    private float originalQuantityOrderedField;
    
    private float originalQuantityBackOrderedField;
    
    private string unitOfMeasureField;
    
    private string serialNumberField;
    
    private string lotNumberField;
    
    private System.DateTime expiryDateField;
    
    private bool expiryDateFieldSpecified;
    
    private float unitPriceExTaxField;
    
    private float unitPriceIncTaxField;
    
    private float taxAmountField;
    
    private float gstField;
    
    private float extendedExTaxField;
    
    private float extendedIncTaxField;
    
    private float miscellaneousCharge1Field;
    
    private float miscellaneousCharge2Field;
    
    private float discountField;
    
    private float lineTotalExcTaxField;
    
    private float lineTotalIncTaxField;
    
    private float recommendedRetailPriceField;
    
    private float weightField;
    
    private float volumeField;
    
    private string userDefinedField1Field;
    
    private string userDefinedField2Field;
    
    private string userDefinedField3Field;
    
    private string userDefinedField4Field;
    
    private string userDefinedField5Field;
    
    private string userDefinedField6Field;
    
    private string userDefinedField7Field;
    
    private string userDefinedField8Field;
    
    private string userDefinedField9Field;
    
    private string userDefinedField10Field;
    
    private bool nonStockItemField;
    
    private string holdCodeField;
    
    private bool kitFlagField;
    
    private SalesOrdersOrderHeaderOrderDetailOrderLotSerial orderLotSerialField;
    
    public SalesOrdersOrderHeaderOrderDetail() {
        this.packingQuantityField = ((float)(0F));
        this.quantityOrderedField = ((float)(0F));
        this.quantityShippedField = ((float)(0F));
        this.quantityBackOrderedField = ((float)(0F));
        this.originalQuantityOrderedField = ((float)(0F));
        this.originalQuantityBackOrderedField = ((float)(0F));
        this.unitPriceExTaxField = ((float)(0F));
        this.unitPriceIncTaxField = ((float)(0F));
        this.taxAmountField = ((float)(0F));
        this.gstField = ((float)(0F));
        this.extendedExTaxField = ((float)(0F));
        this.extendedIncTaxField = ((float)(0F));
        this.miscellaneousCharge1Field = ((float)(0F));
        this.miscellaneousCharge2Field = ((float)(0F));
        this.discountField = ((float)(0F));
        this.lineTotalExcTaxField = ((float)(0F));
        this.lineTotalIncTaxField = ((float)(0F));
        this.recommendedRetailPriceField = ((float)(0F));
        this.weightField = ((float)(0F));
        this.volumeField = ((float)(0F));
        this.nonStockItemField = false;
        this.kitFlagField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string lineNumber {
        get {
            return this.lineNumberField;
        }
        set {
            this.lineNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string customerLineNumber {
        get {
            return this.customerLineNumberField;
        }
        set {
            this.customerLineNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string parentLineNumber {
        get {
            return this.parentLineNumberField;
        }
        set {
            this.parentLineNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string productCode {
        get {
            return this.productCodeField;
        }
        set {
            this.productCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string customerProductCode {
        get {
            return this.customerProductCodeField;
        }
        set {
            this.customerProductCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string upcCode {
        get {
            return this.upcCodeField;
        }
        set {
            this.upcCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string productDescription {
        get {
            return this.productDescriptionField;
        }
        set {
            this.productDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string size {
        get {
            return this.sizeField;
        }
        set {
            this.sizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string style {
        get {
            return this.styleField;
        }
        set {
            this.styleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string category1 {
        get {
            return this.category1Field;
        }
        set {
            this.category1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string category2 {
        get {
            return this.category2Field;
        }
        set {
            this.category2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string category3 {
        get {
            return this.category3Field;
        }
        set {
            this.category3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string category4 {
        get {
            return this.category4Field;
        }
        set {
            this.category4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ageCode {
        get {
            return this.ageCodeField;
        }
        set {
            this.ageCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string seasonCode {
        get {
            return this.seasonCodeField;
        }
        set {
            this.seasonCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float packingQuantity {
        get {
            return this.packingQuantityField;
        }
        set {
            this.packingQuantityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public float quantityOrdered {
        get {
            return this.quantityOrderedField;
        }
        set {
            this.quantityOrderedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float quantityShipped {
        get {
            return this.quantityShippedField;
        }
        set {
            this.quantityShippedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float quantityBackOrdered {
        get {
            return this.quantityBackOrderedField;
        }
        set {
            this.quantityBackOrderedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float originalQuantityOrdered {
        get {
            return this.originalQuantityOrderedField;
        }
        set {
            this.originalQuantityOrderedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float originalQuantityBackOrdered {
        get {
            return this.originalQuantityBackOrderedField;
        }
        set {
            this.originalQuantityBackOrderedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string unitOfMeasure {
        get {
            return this.unitOfMeasureField;
        }
        set {
            this.unitOfMeasureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string serialNumber {
        get {
            return this.serialNumberField;
        }
        set {
            this.serialNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string lotNumber {
        get {
            return this.lotNumberField;
        }
        set {
            this.lotNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime expiryDate {
        get {
            return this.expiryDateField;
        }
        set {
            this.expiryDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool expiryDateSpecified {
        get {
            return this.expiryDateFieldSpecified;
        }
        set {
            this.expiryDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float unitPriceExTax {
        get {
            return this.unitPriceExTaxField;
        }
        set {
            this.unitPriceExTaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float unitPriceIncTax {
        get {
            return this.unitPriceIncTaxField;
        }
        set {
            this.unitPriceIncTaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float taxAmount {
        get {
            return this.taxAmountField;
        }
        set {
            this.taxAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float gst {
        get {
            return this.gstField;
        }
        set {
            this.gstField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float extendedExTax {
        get {
            return this.extendedExTaxField;
        }
        set {
            this.extendedExTaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float extendedIncTax {
        get {
            return this.extendedIncTaxField;
        }
        set {
            this.extendedIncTaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float miscellaneousCharge1 {
        get {
            return this.miscellaneousCharge1Field;
        }
        set {
            this.miscellaneousCharge1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float miscellaneousCharge2 {
        get {
            return this.miscellaneousCharge2Field;
        }
        set {
            this.miscellaneousCharge2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float discount {
        get {
            return this.discountField;
        }
        set {
            this.discountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float lineTotalExcTax {
        get {
            return this.lineTotalExcTaxField;
        }
        set {
            this.lineTotalExcTaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float lineTotalIncTax {
        get {
            return this.lineTotalIncTaxField;
        }
        set {
            this.lineTotalIncTaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float recommendedRetailPrice {
        get {
            return this.recommendedRetailPriceField;
        }
        set {
            this.recommendedRetailPriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float volume {
        get {
            return this.volumeField;
        }
        set {
            this.volumeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string userDefinedField1 {
        get {
            return this.userDefinedField1Field;
        }
        set {
            this.userDefinedField1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string userDefinedField2 {
        get {
            return this.userDefinedField2Field;
        }
        set {
            this.userDefinedField2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string userDefinedField3 {
        get {
            return this.userDefinedField3Field;
        }
        set {
            this.userDefinedField3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string userDefinedField4 {
        get {
            return this.userDefinedField4Field;
        }
        set {
            this.userDefinedField4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string userDefinedField5 {
        get {
            return this.userDefinedField5Field;
        }
        set {
            this.userDefinedField5Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string userDefinedField6 {
        get {
            return this.userDefinedField6Field;
        }
        set {
            this.userDefinedField6Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string userDefinedField7 {
        get {
            return this.userDefinedField7Field;
        }
        set {
            this.userDefinedField7Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string userDefinedField8 {
        get {
            return this.userDefinedField8Field;
        }
        set {
            this.userDefinedField8Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string userDefinedField9 {
        get {
            return this.userDefinedField9Field;
        }
        set {
            this.userDefinedField9Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string userDefinedField10 {
        get {
            return this.userDefinedField10Field;
        }
        set {
            this.userDefinedField10Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool nonStockItem {
        get {
            return this.nonStockItemField;
        }
        set {
            this.nonStockItemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string holdCode {
        get {
            return this.holdCodeField;
        }
        set {
            this.holdCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool kitFlag {
        get {
            return this.kitFlagField;
        }
        set {
            this.kitFlagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SalesOrdersOrderHeaderOrderDetailOrderLotSerial OrderLotSerial {
        get {
            return this.orderLotSerialField;
        }
        set {
            this.orderLotSerialField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SalesOrdersOrderHeaderOrderDetailOrderLotSerial {
    
    private string lotSerialNumberField;
    
    private bool quantityOrderedField;
    
    public SalesOrdersOrderHeaderOrderDetailOrderLotSerial() {
        this.quantityOrderedField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string lotSerialNumber {
        get {
            return this.lotSerialNumberField;
        }
        set {
            this.lotSerialNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool quantityOrdered {
        get {
            return this.quantityOrderedField;
        }
        set {
            this.quantityOrderedField = value;
        }
    }
}
