//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Xml.Serialization;

namespace _3PLPrototype.DataFiles.RuleEngine
{
}

namespace ValidationRuleEngine.DataFiles.RuleEngine
{
}

// 
// This source code was auto-generated by xsd, Version=4.7.2558.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(AnonymousType=true)]
[XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ConfigurationStore {
    
    private Config[] itemsField;
    
    /// <remarks/>
    [XmlElementAttribute("Config", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Config[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(AnonymousType=true)]
public partial class Config {
    
    private Rule[] rulesField;
    
    private string nameField;
    
    private string source_file_pathField;
    
    private bool enabledField;

    private List<Attribute> attributeArray;

    [XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [XmlArrayItemAttribute("attribute", typeof(Attribute), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public List<Attribute> attributes
    {
        get
        {
            return this.attributeArray;
        }
        set
        {
            this.attributeArray = value;
        }
    }

    /// <remarks/>
    [XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [XmlArrayItemAttribute("rule", typeof(Rule), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public Rule[] rules {
        get {
            return this.rulesField;
        }
        set {
            this.rulesField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
        
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string source_file_path {
        get {
            return this.source_file_pathField;
        }
        set {
            this.source_file_pathField = value;
        }
    }

    /// <remarks/>
    [XmlAttributeAttribute()]
    public bool enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
    
}


public partial class Attribute
{
    private string nameField;
    private string valueField;
    private string pathField;
    private bool isRectifiableField;
    private bool enabledField;

    [XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    [XmlAttributeAttribute()]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }

    [XmlAttributeAttribute()]
    public string path
    {
        get
        {
            return this.pathField;
        }
        set
        {
            this.pathField = value;
        }
    }

    [XmlAttributeAttribute()]
    public Boolean is_rectifiable
    {
        get
        {
            return this.isRectifiableField;
        }
        set
        {
            this.isRectifiableField = value;
        }
    }

    [XmlAttributeAttribute()]
    public Boolean enabled
    {
        get
        {
            return this.enabledField;
        }
        set
        {
            this.enabledField = value;
        }
    }

}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(AnonymousType=true)]
public partial class Rule {
    
    private string xpathField;
    
    private string pathField;
    
    private Validation[] validationsField;
    
    private Action[] actionsField;
    
    private string nameField;

    private bool enabledField;
    
    /// <remarks/>
    [XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string xpath {
        get {
            return this.xpathField;
        }
        set {
            this.xpathField = value;
        }
    }
    
    /// <remarks/>
    [XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    [XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [XmlArrayItemAttribute("validation", typeof(Validation), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public Validation[] validations {
        get {
            return this.validationsField;
        }
        set {
            this.validationsField = value;
        }
    }
    
    /// <remarks/>
    [XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [XmlArrayItemAttribute("action", typeof(Action), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public Action[] actions {
        get {
            return this.actionsField;
        }
        set {
            this.actionsField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }

    [XmlAttributeAttribute()]
    public bool enabled
    {
        get
        {
            return this.enabledField;
        }
        set
        {
            this.enabledField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(AnonymousType = true)]
public partial class Validation {

    private string nameField;

    private string typeField;

    [XmlAttribute("validator_type")]
    public string validator_type { get; set; }

    [XmlAttribute("enabled")]
    public bool enabled { get; set; }

    /// <remarks/>
    [XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    [XmlArrayAttribute("attributes")]
    [XmlArrayItemAttribute("attribute")]
    public List<Attribute> LocalAttributes;

    //[XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //[XmlArrayItemAttribute("attribute", typeof(Attribute), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    //public List<Attribute> LocalAttributes
    //{
    //    get
    //    {
    //        return this.localAttributes;
    //    }
    //    set
    //    {
    //        this.localAttributes = value;
    //    }
    //}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(AnonymousType=true)]
public partial class Action {
    
    private string toField;
    
    private string fromField;
    
    private string subjectField;
    
    private string successMessageField;
    
    private string failureMessageField;
    
    private string nameField;
    
    private string typeField;
    
    private string executeOnField;
    
    /// <remarks/>
    [XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string to {
        get {
            return this.toField;
        }
        set {
            this.toField = value;
        }
    }
    
    /// <remarks/>
    [XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string from {
        get {
            return this.fromField;
        }
        set {
            this.fromField = value;
        }
    }
    
    /// <remarks/>
    [XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string subject {
        get {
            return this.subjectField;
        }
        set {
            this.subjectField = value;
        }
    }
    
    /// <remarks/>
    [XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string successMessage {
        get {
            return this.successMessageField;
        }
        set {
            this.successMessageField = value;
        }
    }
    
    /// <remarks/>
    [XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string failureMessage {
        get {
            return this.failureMessageField;
        }
        set {
            this.failureMessageField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string executeOn {
        get {
            return this.executeOnField;
        }
        set {
            this.executeOnField = value;
        }
    }
}
