//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace ValidationRuleEngine.DataFiles.RuleEngine
{
}

// 
// This source code was auto-generated by xsd, Version=4.7.2558.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(AnonymousType=true)]
[XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ConfigurationStore {
    
    private Config[] itemsField;
    
    /// <remarks/>
    [XmlElementAttribute("Config", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Config[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(AnonymousType=true)]
public partial class Config {
    
    private Rule[] rulesField;
    
    private string nameField;
    
    private string xsd_file_pathField;
    
    private string source_file_pathField;
    
    private string success_folder_pathField;
    
    private string failed_folder_pathField;
    
    private bool enabledField;

    private bool customValidationEnabledField;

    private bool xsdValidationEnabledField;
    
    /// <remarks/>
    [XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [XmlArrayItemAttribute("rule", typeof(Rule), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public Rule[] rules {
        get {
            return this.rulesField;
        }
        set {
            this.rulesField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string xsd_file_path {
        get {
            return this.xsd_file_pathField;
        }
        set {
            this.xsd_file_pathField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string source_file_path {
        get {
            return this.source_file_pathField;
        }
        set {
            this.source_file_pathField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string success_folder_path {
        get {
            return this.success_folder_pathField;
        }
        set {
            this.success_folder_pathField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string failed_folder_path {
        get {
            return this.failed_folder_pathField;
        }
        set {
            this.failed_folder_pathField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public bool enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }

    [XmlAttributeAttribute()]
    public bool custom_validation_enabled
    {
        get {
            return customValidationEnabledField;
        }

        set {
            customValidationEnabledField = value;
        }
    }

    [XmlAttributeAttribute()]
    public bool xsd_validation_enabled
    {
        get {
            return this.xsdValidationEnabledField;
        }
        set {
            this.xsdValidationEnabledField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(AnonymousType=true)]
public partial class Rule {
    
    private string xpathField;
    
    private string pathField;
    
    private Validation[] validationsField;
    
    private Action[] actionsField;
    
    private string nameField;
    
    /// <remarks/>
    [XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string xpath {
        get {
            return this.xpathField;
        }
        set {
            this.xpathField = value;
        }
    }
    
    /// <remarks/>
    [XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    [XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [XmlArrayItemAttribute("validation", typeof(Validation), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public Validation[] validations {
        get {
            return this.validationsField;
        }
        set {
            this.validationsField = value;
        }
    }
    
    /// <remarks/>
    [XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [XmlArrayItemAttribute("action", typeof(Action), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public Action[] actions {
        get {
            return this.actionsField;
        }
        set {
            this.actionsField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(AnonymousType=true)]
public partial class Validation {
    
    private string lengthField;
    
    private string messageField;
    
    private string nameField;
    
    private string typeField;
    
    /// <remarks/>
    [XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string length {
        get {
            return this.lengthField;
        }
        set {
            this.lengthField = value;
        }
    }
    
    /// <remarks/>
    [XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(AnonymousType=true)]
public partial class Action {
    
    private string toField;
    
    private string fromField;
    
    private string subjectField;
    
    private string successMessageField;
    
    private string failureMessageField;
    
    private string nameField;
    
    private string typeField;
    
    private string executeOnField;
    
    /// <remarks/>
    [XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string to {
        get {
            return this.toField;
        }
        set {
            this.toField = value;
        }
    }
    
    /// <remarks/>
    [XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string from {
        get {
            return this.fromField;
        }
        set {
            this.fromField = value;
        }
    }
    
    /// <remarks/>
    [XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string subject {
        get {
            return this.subjectField;
        }
        set {
            this.subjectField = value;
        }
    }
    
    /// <remarks/>
    [XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string successMessage {
        get {
            return this.successMessageField;
        }
        set {
            this.successMessageField = value;
        }
    }
    
    /// <remarks/>
    [XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string failureMessage {
        get {
            return this.failureMessageField;
        }
        set {
            this.failureMessageField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string executeOn {
        get {
            return this.executeOnField;
        }
        set {
            this.executeOnField = value;
        }
    }
}
